
# this is needed for the edge functions to know where to find the code
project_id = "xwnoacxhjtokobclmsdq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true

[storage]
enabled = true

[realtime]
enabled = true

[functions]
[functions.create-chargebee-page]
verify_jwt = true

[functions.chargebee-webhook]
verify_jwt = false # webhook needs to be public
