// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwnoacxhjtokobclmsdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3bm9hY3hoanRva29iY2xtc2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzY4MzIsImV4cCI6MjA2MjIxMjgzMn0.OZighHD9DEe01DbCp5AdLeQzsdLMvOFLp40t3YG8nMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);